Repository mongodb/mongo-csharp-driver, pull requests merged in 2025-07, with the labels that each got.

#1716 CSHARP-5608: CSOT: Command Execution
  src/MongoDB.Driver/Authentication/MongoDBX509Authenticator.cs
  src/MongoDB.Driver/Authentication/SaslAuthenticator.cs
  src/MongoDB.Driver/Core/Bindings/IChannel.cs
  src/MongoDB.Driver/Core/Bindings/ServerChannelSource.cs
  src/MongoDB.Driver/Core/Clusters/Cluster.cs
  src/MongoDB.Driver/Core/Clusters/LoadBalancedCluster.cs
  src/MongoDB.Driver/Core/Compression/SnappyCompressor.cs
  src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
  src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.cs
  src/MongoDB.Driver/Core/Connections/BinaryConnection.cs
  src/MongoDB.Driver/Core/Connections/ConnectionInitializer.cs
  src/MongoDB.Driver/Core/Connections/HelloHelper.cs
  src/MongoDB.Driver/Core/Connections/IConnection.cs
  src/MongoDB.Driver/Core/Misc/SemaphoreSlimRequest.cs
  src/MongoDB.Driver/Core/Misc/StreamExtensionMethods.cs
  src/MongoDB.Driver/Core/Operations/AsyncCursor.cs
  src/MongoDB.Driver/Core/Operations/CommandOperationBase.cs
  src/MongoDB.Driver/Core/Operations/ReadCommandOperation.cs
  src/MongoDB.Driver/Core/Operations/RetryableWriteCommandOperationBase.cs
  src/MongoDB.Driver/Core/Servers/IServer.cs
  src/MongoDB.Driver/Core/Servers/RoundTripTimeMonitor.cs
  src/MongoDB.Driver/Core/Servers/SelectedServer.cs
  src/MongoDB.Driver/Core/Servers/Server.cs
  src/MongoDB.Driver/Core/Servers/ServerChannel.cs
  src/MongoDB.Driver/Core/Servers/ServerMonitor.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandUsingQueryMessageWireProtocol.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandWireProtocol.cs
  src/MongoDB.Driver/Core/WireProtocol/IWireProtocol.cs
  src/MongoDB.Driver/OperationContext.cs
  src/MongoDB.Driver/OperationExecutor.cs
  tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
  tests/MongoDB.Driver.Tests/AuthenticationTests.cs
  tests/MongoDB.Driver.Tests/ClusterTests.cs
  tests/MongoDB.Driver.Tests/Core/Bindings/ServerChannelSourceTests.cs
  tests/MongoDB.Driver.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnectionTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnection_CommandEventTests.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3173Tests.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3302Tests.cs
  tests/MongoDB.Driver.Tests/Core/Misc/StreamExtensionMethodsTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/AsyncCursorTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/ReadCommandOperationTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/WriteCommandOperationTests.cs
  tests/MongoDB.Driver.Tests/Core/Servers/LoadBalancedServerTests.cs
  tests/MongoDB.Driver.Tests/Core/Servers/RoundTripTimeMonitorTests.cs
  tests/MongoDB.Driver.Tests/Core/Servers/ServerTests.cs
  tests/MongoDB.Driver.Tests/Core/WireProtocol/CommandWriteProtocolTests.cs
  tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
  tests/MongoDB.Driver.Tests/IJsonDrivenTestRunner.cs
  tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenConfigureFailPointTest.cs
  tests/MongoDB.Driver.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
  tests/MongoDB.Driver.Tests/Specifications/mongodb-handshake/MongoDbHandshakeProseTests.cs
  tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringTestRunner.cs
Labels: feature

#1708 CSHARP-3458: Extend IAsyncCursor and IAsyncCursorSource to support IAsyncEnumerable
  src/MongoDB.Driver/Core/IAsyncCursor.cs
  src/MongoDB.Driver/Core/IAsyncCursorSource.cs
  src/MongoDB.Driver/Core/Operations/AsyncCursorEnumerableOneTimeAdapter.cs
  src/MongoDB.Driver/Core/Operations/AsyncCursorEnumerator.cs
  src/MongoDB.Driver/Core/Operations/AsyncCursorSourceEnumerableAdapter.cs
  src/MongoDB.Driver/Core/Operations/AsyncCursorSourceEnumerator.cs
  src/MongoDB.Driver/Linq/MongoQueryable.cs
  tests/MongoDB.Driver.Tests/BulkWriteErrorTests.cs
  tests/MongoDB.Driver.Tests/Core/IAsyncCursorExtensionsTests.cs
  tests/MongoDB.Driver.Tests/Core/IAsyncCursorSourceExtensionsTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/AsyncCursorEnumerableOneTimeAdapterTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/AsyncCursorEnumeratorTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/AsyncCursorSourceEnumeratorTests.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableTests.cs
Labels: improvement

#1727 CSHARP-5582: Assert unset BulkWriteException.partialResult in CRUD prose tests
  src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
  tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
Labels: chore

#1724 CSHARP-5588: Unable to select KeyValuePair Key when using camelCase convention
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewKeyValuePairExpressionToAggregationExpressionTranslator.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewKeyValuePairExpressionToAggregationExpressionTranslatorTests.cs
Labels: bug

#1723 CSHARP-5642: Temporary disable mongocryptd tests on latest, windows
  tests/MongoDB.Driver.TestHelpers/Core/CoreTestConfiguration.cs
  tests/MongoDB.Driver.Tests/Encryption/AutoEncryptionTests.cs
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
  tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
  tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LibmongocryptTests.cs
Labels: chore

#1722 CSHARP-5633: BsonSerializer.IsTypeDiscriminated is not thread-safe
  src/MongoDB.Bson/Serialization/BsonSerializer.cs
Labels: bug

#1725 CSHARP-5568: Remove Serverless testing
  build.cake
  evergreen/evergreen.yml
  evergreen/run-serverless-tests.sh
  tests/AtlasConnectivity.Tests/ConnectivityTests.cs
  tests/MongoDB.Driver.TestHelpers/Core/CoreTestConfiguration.cs
  tests/MongoDB.Driver.TestHelpers/Core/XunitExtensions/RequireServer.cs
  tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
  tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
  tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
  tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
Labels: chore

#1734 CSHARP-5648: Fix ClientEncryptionProseTests.BypassSpawningMongocryptdViaMongocryptdBypassSpawnTest
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Labels: chore

#1735 CSHARP-5395: Add test to ensure network errors match isClientError
  specifications/crud/tests/unified/estimatedDocumentCount.json
  specifications/crud/tests/unified/estimatedDocumentCount.yml
  specifications/unified-test-format/tests/valid-pass/expectedError-isClientError.json
  specifications/unified-test-format/tests/valid-pass/expectedError-isClientError.yml
Labels: chore

#1736 CSHARP-5388: Allow drivers to set bypassDocumentValidation: false on write commands
  specifications/crud/tests/unified/bypassDocumentValidation.json
  specifications/crud/tests/unified/bypassDocumentValidation.yml
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAggregateOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedBulkWriteOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedFindOneAndReplaceOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedFindOneAndUpdateOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedInsertManyOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedReplaceOneOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedUpdateManyOperation.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedUpdateOneOperation.cs
Labels: chore

#1720 CSHARP-3538: CSOT: Auth
  src/MongoDB.Driver/Authentication/AuthenticationHelper.cs
  src/MongoDB.Driver/Authentication/DefaultAuthenticator.cs
  src/MongoDB.Driver/Authentication/IAuthenticator.cs
  src/MongoDB.Driver/Authentication/MongoDBX509Authenticator.cs
  src/MongoDB.Driver/Authentication/SaslAuthenticator.cs
  src/MongoDB.Driver/Core/Configuration/ClusterBuilder.cs
  src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
  src/MongoDB.Driver/Core/Connections/BinaryConnection.cs
  src/MongoDB.Driver/Core/Connections/ConnectionInitializer.cs
  src/MongoDB.Driver/Core/Connections/HelloHelper.cs
  src/MongoDB.Driver/Core/Connections/IConnection.cs
  src/MongoDB.Driver/Core/Connections/IConnectionInitializer.cs
  src/MongoDB.Driver/Core/Servers/RoundTripTimeMonitor.cs
  src/MongoDB.Driver/Core/Servers/ServerMonitor.cs
  src/MongoDB.Driver/Core/Servers/ServerMonitorSettings.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
  src/MongoDB.Driver/OperationContext.cs
  tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
  tests/MongoDB.Driver.Tests/Authentication/AuthenticationHelperTests.cs
  tests/MongoDB.Driver.Tests/Authentication/MongoAWSAuthenticatorTests.cs
  tests/MongoDB.Driver.Tests/Authentication/MongoDBX509AuthenticatorTests.cs
  tests/MongoDB.Driver.Tests/Authentication/PlainAuthenticatorTests.cs
  tests/MongoDB.Driver.Tests/Authentication/ScramSha1AuthenticatorTests.cs
  tests/MongoDB.Driver.Tests/Authentication/ScramSha256AuthenticatorTests.cs
  tests/MongoDB.Driver.Tests/Core/Configuration/ClusterBuilderTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnectionTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnection_CommandEventTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/ConnectionInitializerTests.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3173Tests.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3302Tests.cs
  tests/MongoDB.Driver.Tests/Core/Servers/RoundTripTimeMonitorTests.cs
  tests/MongoDB.Driver.Tests/Core/Servers/ServerMonitorTests.cs
  tests/MongoDB.Driver.Tests/Specifications/mongodb-handshake/MongoDbHandshakeProseTests.cs
Labels: feature

#1737 CSHARP-5521: Test IPv6 literal in SDAM
  specifications/server-discovery-and-monitoring/tests/rs/secondary_ipv6_literal.json
  specifications/server-discovery-and-monitoring/tests/rs/secondary_ipv6_literal.yml
Labels: chore

#1741 CSHARP-5650: Fix cluster location in atlas-search-index tests
  evergreen/evergreen.yml
Labels: chore

#1733 CSHARP-5392: Add integration tests for transactions write concern behavior
  tests/MongoDB.Driver.Tests/Specifications/transactions/TransactionsProseTests.cs
Labels: chore

#1738 CSHARP-5373: Add test that PoolClearedEvent is emitted before ConnectionCheckedInEvent/ConnectionCheckOutFailedEvent
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-application-error.json
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-application-error.yml
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-checkout-error.json
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-checkout-error.yml
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-min-pool-size-error.json
  specifications/server-discovery-and-monitoring/tests/unified/pool-clear-min-pool-size-error.yml
Labels: chore

#1739 CSHARP-5391: Add spec test for $$type operator with "number"
  specifications/unified-test-format/tests/valid-pass/operator-type-number_alias.json
  specifications/unified-test-format/tests/valid-pass/operator-type-number_alias.yml
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
Labels: chore

#1730 CSHARP-5379: Add mixed case tests for read preference tags
  specifications/uri-options/tests/read-preference-options.json
  specifications/uri-options/tests/read-preference-options.yml
Labels: chore

#1744 CSHARP-5685: Use dotnet 9.0 SDK to build efcore tests
  evergreen/evergreen.yml
  evergreen/install-dotnet.sh
Labels: chore
