Repository mongodb/mongo-csharp-driver, pull requests merged in 2025-05, with the labels that each got.

#1678 CSHARP-5543: Add new options for Atlas Search Text and Phrase operators
  src/MongoDB.Driver/Search/MatchCriteria.cs
  src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
  src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
  src/MongoDB.Driver/Search/SearchPhraseOptions.cs
  src/MongoDB.Driver/Search/SearchTextOptions.cs
  tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
  tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
Labels: feature

#1681 CSHARP-5583: Update README.md
  README.md
Labels: chore

#1689 DEVPROD-17449 - Replace perf.send with new direct end point for performance data submission
  evergreen/evergreen.yml
Labels: chore

#1680 CSHARP-4918: Release notes automation
  .github/workflows/pr.yml
  evergreen/release-notes.py
Labels: chore

#1692 CSHARP-5591: Configure MongoDB.Driver.Encryption.Tests to run on net472 target
  build.cake
  build.ps1
  build.sh
  tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
  tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
  tests/BuildProps/Tests.Build.props
  tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
  tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
  tests/MongoDB.Driver.Encryption.Tests/MongoDB.Driver.Encryption.Tests.csproj
  tests/MongoDB.Driver.Encryption.Tests/xunit.runner.json
  tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
  tests/MongoDB.Driver.TestHelpers/MongoDB.Driver.TestHelpers.csproj
  tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
Labels: chore

#1686 CSHARP-3435: FilterDefinition Inject method should use root serializer
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3435Tests.cs
Labels: bug

#1693 CSHARP-5539: Update Atlas Search tests for rankFusion
  tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
Labels: chore

#1699 CSHARP-5598: Fix CoreServerSessionPool.IsAboutToExpire test
  tests/MongoDB.Driver.Tests/Core/Bindings/CoreServerSessionPoolTests.cs
Labels: chore

#1702 CSHARP-5585: Remove reliance on Evergreen instance profile credentials
  evergreen/evergreen.yml
Labels: chore

#1704 CSHARP-5585: Remove reliance on Evergreen instance profile credentials
  evergreen/evergreen.yml
Labels: chore
