Repository mongodb/mongo-csharp-driver, pull requests merged in 2025-04, with the labels that each got.

#1651 CSHARP-5340: Test encoding dates after year 9999 with Relaxed Extended…
  specifications/bson-corpus/tests/datetime.json
Labels: chore

#1656 CSHARP-5371: URI options spec tests specify may empty options
  specifications/uri-options/tests/compression-options.json
  specifications/uri-options/tests/compression-options.yml
  specifications/uri-options/tests/concern-options.json
  specifications/uri-options/tests/concern-options.yml
  specifications/uri-options/tests/connection-options.json
  specifications/uri-options/tests/connection-options.yml
  specifications/uri-options/tests/connection-pool-options.json
  specifications/uri-options/tests/connection-pool-options.yml
  specifications/uri-options/tests/read-preference-options.json
  specifications/uri-options/tests/read-preference-options.yml
  specifications/uri-options/tests/sdam-options.json
  specifications/uri-options/tests/sdam-options.yml
  specifications/uri-options/tests/single-threaded-options.json
  specifications/uri-options/tests/single-threaded-options.yml
  specifications/uri-options/tests/srv-options.json
  specifications/uri-options/tests/srv-options.yml
  specifications/uri-options/tests/tls-options.json
  specifications/uri-options/tests/tls-options.yml
  tests/MongoDB.Driver.Tests/Specifications/connection-string/ConnectionStringTestRunner.cs
Labels: chore

#1660 CSHARP-5550: Change streams expanded events present by default in 8.2+
  specifications/change-streams/tests/unified/change-streams-disambiguatedPaths.json
  specifications/change-streams/tests/unified/change-streams-disambiguatedPaths.yml
  specifications/change-streams/tests/unified/change-streams.json
  specifications/change-streams/tests/unified/change-streams.yml
Labels: chore

#1661 CSHARP-5551: Support KeyValuePair.Create<TKey,TValue>method in LINQ
  src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/KeyValuePairMethod.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CreateMethodToAggregationExpressionTranslator.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewKeyValuePairExpressionToAggregationExpressionTranslator.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewKeyValuePairExpressionToAggregationExpressionTranslatorTests.cs
Labels: feature

#1663 CSHARP-5559: Update Microsoft.NET.Test.Sdk to 17.13.0 for s390x compatibility
  tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
  tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
  tests/MongoDB.Driver.Encryption.Tests/MongoDB.Driver.Encryption.Tests.csproj
  tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
  tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
  tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
Labels: chore

#1662 CSHARP-5530: Revise assertion for unacknowledged client bulkWrite result
  specifications/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.json
  specifications/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.yml
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
  tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedClientBulkWriteOperation.cs
Labels: chore

#1666 CSHARP-5372: Sync tests for null insert/upsert _id values
  specifications/crud/tests/unified/create-null-ids.json
  specifications/crud/tests/unified/create-null-ids.yml
Labels: chore

#1664 CSHARP-5533: Fix failing OCSP test variants
  evergreen/evergreen.yml
  evergreen/prepare-ocsp.sh
Labels: chore

#1659 CSHARP-5552: Add support for $convert in LINQ
  src/MongoDB.Bson/Serialization/Serializers/ByteSerializer.cs
  src/MongoDB.Bson/Serialization/Serializers/Int16Serializer.cs
  src/MongoDB.Bson/Serialization/Serializers/SByteSerializer.cs
  src/MongoDB.Bson/Serialization/Serializers/SingleSerializer.cs
  src/MongoDB.Bson/Serialization/Serializers/UInt16Serializer.cs
  src/MongoDB.Bson/Serialization/Serializers/UInt64Serializer.cs
  src/MongoDB.Driver/ConvertOptions.cs
  src/MongoDB.Driver/Core/Misc/Feature.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Ast/AstEnumExtensions.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstConvertExpression.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstExpression.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/MqlMethod.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodCallExpressionToAggregationExpressionTranslator.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ConvertMethodToAggregationExpressionTranslator.cs
  src/MongoDB.Driver/Mql.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Ast/Expressions/AstExpressionTests.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ConvertMethodToAggregationExpressionTranslatorTests.cs
Labels: feature

#1670 CSHARP-5531:Reduce memory allocations in BsonStreamAdapter.WriteDouble and WriteInt64
  src/MongoDB.Bson/IO/BsonStreamAdapter.cs
Labels: improvement

#1605 CSHARP-5471: Incorrectly resolving the authentication mechanism param…
  src/MongoDB.Driver/Core/Configuration/ConnectionString.cs
  tests/MongoDB.Driver.Tests/MongoCredentialTests.cs
Labels: bug

#1674 CSHARP-5574: Fix EFCore encryption tests failure in C# Driver CI
  evergreen/evergreen.yml
Labels: chore

#1667 CSHARP-5370: Test driver-generated '_id' fields are first in documents
  tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
Labels: chore

#1665 CSHARP-5204: Test Heartbeats don't gossip cluster time
  tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
Labels: chore

#1621 CSHARP-5505: Add $geoNear stage aggregation builders
  src/MongoDB.Driver/Core/Misc/Feature.cs
  src/MongoDB.Driver/Core/Operations/GeoNearOperation.cs
  src/MongoDB.Driver/GeoNearOptions.cs
  src/MongoDB.Driver/IAggregateFluentExtensions.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Stages/AstGeoNearStage.cs
  src/MongoDB.Driver/PipelineDefinitionBuilder.cs
  src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
  tests/MongoDB.Driver.Tests/AggregateGeoNearTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/GeoNearOperationTests.cs
  tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
  tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
Labels: feature

#1677 CSHARP-4918: Release notes automation
  evergreen/evergreen.yml
  evergreen/generate-release-notes.sh
  evergreen/patch-notes.yml
  evergreen/release-notes.py
  evergreen/release-notes.yml
Labels: chore

#1419 CSHARP-4935: Support casting from an interface to a type that implements that interface in LINQ queries
  src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
  src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ToFilterFieldTranslators/ConvertExpressionToFilterFieldTranslator.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslatorTests.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConvertExpressionToFilterTranslatorTests.cs
Labels: feature

#1583 CSHARP-5442: Fixed use of serializer by Atlas Search operators
  src/MongoDB.Driver/FieldValueSerializerHelper.cs
  src/MongoDB.Driver/IAggregateFluent.cs
  src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
  src/MongoDB.Driver/Search/SearchDefinition.cs
  src/MongoDB.Driver/Search/SearchPathDefinition.cs
  src/MongoDB.Driver/Search/SearchPathDefinitionBuilder.cs
  tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
Labels: bug

#1679 CSHARP-5579: Fix timeouts in CSE custom endpoint test
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Labels: chore

#1653 CSHARP-5529: Optimize grouping.First().X to not retrieve the entire $$ROOT
  src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstGroupingPipelineOptimizer.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5529Tests.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableTests.cs
  tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/Translators/AggregateGroupTranslatorTests.cs
  tests/MongoDB.Driver.Tests/Samples/AggregationSample.cs
Labels: improvement
