Repository mongodb/mongo-csharp-driver, pull requests merged in 2025-06, with the labels that each got.

#1684 CSHARP4040: Fix bug when using field with same element name as discriminator
  src/MongoDB.Bson/Serialization/BsonClassMap.cs
  src/MongoDB.Bson/Serialization/Conventions/StandardDiscriminatorConvention.cs
  tests/MongoDB.Bson.Tests/Serialization/Conventions/StandardDiscriminatorConventionTests.cs
  tests/MongoDB.Driver.Tests/Jira/CSharp4040Tests.cs
Labels: bug

#1676 CSHARP-5560: CSOT: Refactor IOperationExecutor to use operation context
  .editorconfig
  src/MongoDB.Driver/AggregateHelper.cs
  src/MongoDB.Driver/IOperationExecutor.cs
  src/MongoDB.Driver/MongoClient.cs
  src/MongoDB.Driver/MongoCollectionImpl.cs
  src/MongoDB.Driver/MongoDatabase.cs
  src/MongoDB.Driver/OperationExecutor.cs
  src/MongoDB.Driver/ReadOperationOptions.cs
  src/MongoDB.Driver/ReadPreferenceResolver.cs
  src/MongoDB.Driver/WriteOperationOptions.cs
  tests/MongoDB.Driver.Tests/MockOperationExecutor.cs
  tests/MongoDB.Driver.Tests/MongoClientTests.cs
  tests/MongoDB.Driver.Tests/MongoDatabaseTests.cs
  tests/MongoDB.Driver.Tests/OperationExecutorTests.cs
  tests/MongoDB.Driver.Tests/ReadOperationOptionsTests.cs
Labels: maintenance

#1685 CSHARP-3494: Fix discriminator for generic types
  src/MongoDB.Bson/Serialization/BsonClassMap.cs
  tests/MongoDB.Bson.Tests/Jira/CSharp515Tests.cs
  tests/MongoDB.Bson.Tests/Serialization/Serializers/DiscriminatorTests.cs
Labels: bug

#1683 CSHARP-5614: Fix deserialization of primitive arrays on Big Endian systems
  src/MongoDB.Bson/Serialization/Serializers/PrimitivesArrayReader.cs
Labels: improvement

#1709 CSHARP-5608: CSOT: Command Execution
  src/MongoDB.Driver/Core/Clusters/Cluster.cs
  src/MongoDB.Driver/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3173Tests.cs
  tests/MongoDB.Driver.Tests/Core/Jira/CSharp3302Tests.cs
  tests/MongoDB.Driver.Tests/Core/Logging/EventLoggerTests.cs
  tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Labels: feature

#1712 CSHARP-5618: CSOT: Race condition in ExclusiveConnectionPool could lead to ArgumentOutOfRangeException
  src/MongoDB.Driver/OperationContext.cs
  tests/MongoDB.Bson.TestHelpers/Threading/ThreadingUtilities.cs
  tests/MongoDB.Driver.Tests/OperationContextTests.cs
Labels: bug

#1713 CSHARP-5619: Replace IConnection.SendMessages with the method to send a single message
  src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
  src/MongoDB.Driver/Core/Connections/BinaryConnection.cs
  src/MongoDB.Driver/Core/Connections/CommandEventHelper.cs
  src/MongoDB.Driver/Core/Connections/ConnectionExtensions.cs
  src/MongoDB.Driver/Core/Connections/IConnection.cs
  src/MongoDB.Driver/Core/Events/ConnectionSendingMessagesEvent.cs
  src/MongoDB.Driver/Core/Events/ConnectionSendingMessagesFailedEvent.cs
  src/MongoDB.Driver/Core/Events/ConnectionSentMessagesEvent.cs
  src/MongoDB.Driver/Core/Events/Diagnostics/PerformanceCounterEventSubscriber.cs
  src/MongoDB.Driver/Core/Events/Diagnostics/TraceSourceEventSubscriber.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandMessageFieldEncryptor.cs
  src/MongoDB.Driver/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
  src/MongoDB.Driver/Core/WireProtocol/Messages/CommandRequestMessage.cs
  src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandRequestMessageBinaryEncoder.cs
  src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/JsonEncoders/CommandRequestMessageJsonEncoder.cs
  src/MongoDB.Driver/Core/WireProtocol/Messages/QueryMessage.cs
  src/MongoDB.Driver/Core/WireProtocol/Messages/RequestMessage.cs
  src/MongoDB.Driver/Core/WireProtocol/WriteWireProtocolBase.cs
  tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnectionTests.cs
  tests/MongoDB.Driver.Tests/Core/Connections/BinaryConnection_CommandEventTests.cs
  tests/MongoDB.Driver.Tests/Core/Helpers/MessageHelper.cs
  tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/CommandRequestMessageTests.cs
  tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandRequestMessageBinaryEncoderTests.cs
  tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/Encoders/BinaryEncoders/QueryMessageBinaryEncoderTests.cs
  tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/Encoders/JsonEncoders/CommandRequestMessageJsonEncoderTests.cs
Labels: improvement

#1717 CSHARP-3537: CSOT: retryable reads and writes
  src/MongoDB.Driver/Core/Operations/BulkMixedWriteOperation.cs
  src/MongoDB.Driver/Core/Operations/BulkUnmixedWriteOperationBase.cs
  src/MongoDB.Driver/Core/Operations/DeleteRequest.cs
  src/MongoDB.Driver/Core/Operations/InsertRequest.cs
  src/MongoDB.Driver/Core/Operations/RetryabilityHelper.cs
  src/MongoDB.Driver/Core/Operations/RetryableReadContext.cs
  src/MongoDB.Driver/Core/Operations/RetryableReadOperationExecutor.cs
  src/MongoDB.Driver/Core/Operations/RetryableWriteContext.cs
  src/MongoDB.Driver/Core/Operations/RetryableWriteOperationExecutor.cs
  src/MongoDB.Driver/Core/Operations/UpdateRequest.cs
  src/MongoDB.Driver/Core/Operations/WriteRequest.cs
  src/MongoDB.Driver/OperationContext.cs
  src/MongoDB.Driver/OperationContextExtensions.cs
  tests/MongoDB.Driver.Tests/Core/Operations/ReadCommandOperationTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/RetryableReadOperationExecutorTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/RetryableWriteOperationExecutorTests.cs
  tests/MongoDB.Driver.Tests/Core/Operations/WriteCommandOperationTests.cs
  tests/MongoDB.Driver.Tests/OperationContextTests.cs
Labels: feature
